"""add payment tracking and vendor profiles

Revision ID: c690a0796172
Revises: cf3d109b3266
Create Date: 2026-06-04 00:34:40.718209

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c690a0796172'
down_revision: Union[str, None] = 'cf3d109b3266'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vendor_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('vendor_name', sa.String(length=255), nullable=False),
    sa.Column('total_invoices', sa.Integer(), nullable=False),
    sa.Column('total_spend', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('average_invoice', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('last_invoice_date', sa.Date(), nullable=True),
    sa.Column('is_recurring_vendor', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'vendor_name', name='uq_vendor_per_tenant')
    )
    op.add_column('extracted_data', sa.Column('is_recurring', sa.Boolean(), nullable=False))
    op.add_column('invoices', sa.Column('payment_status', sa.String(length=20), nullable=False))
    op.add_column('invoices', sa.Column('payment_date', sa.Date(), nullable=True))
    op.add_column('invoices', sa.Column('payment_ref', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoices', 'payment_ref')
    op.drop_column('invoices', 'payment_date')
    op.drop_column('invoices', 'payment_status')
    op.drop_column('extracted_data', 'is_recurring')
    op.drop_table('vendor_profiles')
    # ### end Alembic commands ###
